_core:
  default_config_hash: 7R74wb0NllX6DTTAV9sfg790XV_QXshmF0wAobLEFNQ
langcode: fi
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: false
  favicon: true
  node_user_picture: true
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: red
preset_focus_color: gin
enable_darkmode: false
classic_toolbar: horizontal
icon_default: false
icon_path: themes/custom/druid_theme/images/icon/favicon-32x32.png
high_contrast_mode: false
accent_color: ''
focus_color: ''
icon_upload: ''
show_user_theme_settings: true
